=== Hec734tor/sew/xml/etapa.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	
	<!-- Restricción para el número de etapa (1 a 21) -->
	<xs:simpleType name="TipoNumeroEtapa">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="21"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Restricción para valores que no pueden ser negativos (mayor o igual a 0) -->
	<xs:simpleType name="TipoPositivo">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.0"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Restricción lógica para la Latitud (-90 a 90 grados) -->
	<xs:simpleType name="TipoLatitudRestringida">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90.0"/>
			<xs:maxInclusive value="90.0"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Restricción lógica para la Longitud (-180 a 180 grados) -->
	<xs:simpleType name="TipoLongitudRestringida">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180.0"/>
			<xs:maxInclusive value="180.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreEtapa" />
				<xs:element ref="numeroEtapa" />
				<xs:element ref="longitudEtapa" />
				<xs:element ref="fechaEtapa" />
				<xs:element ref="tiempoGanador" />
				<xs:element ref="velocidadMedia" />
				<xs:element ref="desnivel" />
				<xs:element ref="ciudadSalida" />
				<xs:element ref="ciudadLlegada" />
				<xs:element ref="tipoEtapa" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="galeriaSonidos" />
				<xs:element ref="salida" />
				<xs:element ref="meta" />
				<xs:element ref="hitos" />
				<xs:element ref="clasificacionEtapa" />
				<xs:element ref="clasificacionGeneral" />
				<xs:element ref="clasificacionEquipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombreEtapa" type="xs:string" />
	
	<!-- Aplicamos la restricción del 1 al 21 -->
	<xs:element name="numeroEtapa" type="TipoNumeroEtapa" />
	
	
	<xs:element name="longitudEtapa">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoPositivo">
					<xs:attribute fixed="km" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fechaEtapa" type="xs:date" />
	
	<!-- Tiempos usando  xs:time -->
	<xs:element name="tiempoGanador">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:duration">
					<xs:attribute fixed="hh:mm:ss" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="velocidadMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoPositivo">
					<xs:attribute fixed="km/h" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoPositivo">
					<xs:attribute fixed="m" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ciudadSalida" type="xs:string" />
	<xs:element name="ciudadLlegada" type="xs:string" />
	
	<xs:element name="tipoEtapa">
		<xs:complexType>
			<xs:attribute name="valor" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="llana" />
						<xs:enumeration value="montaña" />
						<xs:enumeration value="contrarrelojIndividual" />
						<xs:enumeration value="contrarrelojEquipos" />
						<xs:enumeration value="mediaMontaña" />
						<xs:enumeration value="ondulada" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<!-- Cardinalidades: mínimo 3 referencias -->
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:anyURI" />
	
	<!-- Cardinalidades: 1 a 5 fotos -->
    <xs:element name="galeriaFotos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="5" ref="foto" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="foto" type="xs:string" />

    <!-- Cardinalidades: 1 a 3 videos -->
    <xs:element name="galeriaVideos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="3" ref="video" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="video" type="xs:string" />

    <!-- Cardinalidades: 1 a 3 sonidos -->
    <xs:element name="galeriaSonidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="3" ref="sonido" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="sonido" type="xs:string" />

	<xs:element name="salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="puertos" />
				<xs:element minOccurs="0" maxOccurs="1" ref="sprints" />
				<xs:element ref="puntosAnonimos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="puertos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="puerto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sprints">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="sprint" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Cardinalidad: estricta entre 20 y 30 puntos -->
	<xs:element name="puntosAnonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="20" maxOccurs="30" ref="puntoAnonimo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="puerto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="tipoPuerto" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="1_categoría" />
						<xs:enumeration value="2_categoría" />
						<xs:enumeration value="3_categoría" />
						<xs:enumeration value="categoria_especial" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sprint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="tipoSprint" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="intermedio" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="puntoAnonimo">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombre" type="xs:string" />
	
	<!-- Coordenadas con dominios lógicos -->
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoLongitudRestringida">
					<xs:attribute fixed="grados" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoLatitudRestringida">
					<xs:attribute fixed="grados" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoPositivo">
					<xs:attribute fixed="m" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoPositivo">
					<xs:attribute fixed="km" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="tiempo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:duration">
					<xs:attribute fixed="hh:mm:ss" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="diferencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:duration">
					<xs:attribute fixed="hh:mm:ss" name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<!-- Clasificaciones limitadas exactamente a 3 integrantes -->
	<xs:element name="clasificacionEtapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificadoEtapa" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificadoEtapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tiempo" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="puesto" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="1" />
						<xs:enumeration value="2" />
						<xs:enumeration value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="equipo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificacionGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificadoGeneral" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificadoGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tiempo" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="puesto" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="1" />
						<xs:enumeration value="2" />
						<xs:enumeration value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="equipo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificacionEquipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificadoEquipo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificadoEquipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tiempo" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="puesto" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="1" />
						<xs:enumeration value="2" />
						<xs:enumeration value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hec734tor/sew/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uniovi.es etapa.xsd"
       xmlns="http://www.uniovi.es">
    <nombreEtapa>Falset. Costa Daurada-Roquetes. Terres de l´Ebre</nombreEtapa>
    <numeroEtapa>5</numeroEtapa>
    <longitudEtapa unidades="km">173.3</longitudEtapa>
    <fechaEtapa>2026-08-26</fechaEtapa>
    <tiempoGanador>PT3H47M2S</tiempoGanador>
    <velocidadMedia unidades="km/h">45.8</velocidadMedia>
    <desnivel unidades="m">1662</desnivel>
    <ciudadSalida>Falset.Costa Daurada</ciudadSalida>
    <ciudadLlegada>Roquetes. Terres</ciudadLlegada>
    <tipoEtapa valor="ondulada"/>

    <referencias>
        <referencia>https://costadaurada.info/</referencia>
        <referencia>https://roquetes.cat/web/</referencia>
        <referencia>https://www.falset.org/</referencia>
        <referencia>https://www.turismepriorat.org/</referencia>
        <referencia>https://terresdelebre.travel</referencia>
    </referencias>

    <galeriaFotos>
        <foto>Salida.jpg</foto>
        <foto>Puerto.jpg</foto>
        <foto>Meta.jpg</foto>
        <foto>Mapa.jpg</foto>
    </galeriaFotos>

    <galeriaVideos>
        <video>ResumenEtapa.mp4</video>
        <video>CimaPuerto.mp4</video>
        <video>LlegadaMeta.mp4</video>
    </galeriaVideos>

    <galeriaSonidos>
        <sonido>PodcastSalida.mp3</sonido>
        <sonido>PodcastRuta.mp3</sonido>
        <sonido>PodcastMeta.mp3</sonido>
    </galeriaSonidos>

    <salida>
        <longitud unidades="grados">0.8185</longitud>
        <latitud unidades="grados">41.1458</latitud>
         <altitud unidades="m" >270 </altitud>

    </salida> 
    <meta>
        <longitud unidades="grados">0.5008</longitud>
        <latitud unidades="grados">40.8194</latitud>
        <altitud unidades="m">25 </altitud>

    </meta> 

    <hitos>
    <puertos>
        <puerto tipoPuerto="3_categoría">
            <nombre>Puerto de Paüls</nombre>
            <longitud unidades="grados">0.4005</longitud>
            <latitud unidades="grados">40.9238</latitud>
            <altitud unidades="m">381</altitud>
            <distancia unidades="km">148.4</distancia>
        </puerto>
    </puertos>

    <sprints>
        <sprint tipoSprint="bonificado">
            <nombre>Tivenys</nombre>
            <longitud unidades="grados">0.5123</longitud>
            <latitud unidades="grados">40.9416</latitud>
            <altitud unidades="m">15</altitud>
            <distancia unidades="km">114.7</distancia>
        </sprint>
    </sprints>
    <puntosAnonimos>
        <!-- Tramo inicial: Falset a Móra la Nova -->
        <puntoAnonimo>
            <nombre>Falset (Salida)</nombre>
            <longitud unidades="grados">0.8185</longitud>
            <latitud unidades="grados">41.1458</latitud>
            <altitud unidades="m">270</altitud>
            <distancia unidades="km">0.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Rotonda Capçanes</nombre>
            <longitud unidades="grados">0.8281</longitud>
            <latitud unidades="grados">41.1005</latitud>
            <altitud unidades="m">220</altitud>
            <distancia unidades="km">2.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Els Guiamets</nombre>
            <longitud unidades="grados">0.7514</longitud>
            <latitud unidades="grados">41.1021</latitud>
            <altitud unidades="m">220</altitud>
            <distancia unidades="km">5.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Móra la Nova</nombre>
            <longitud unidades="grados">0.6506</longitud>
            <latitud unidades="grados">41.1008</latitud>
            <altitud unidades="m">44</altitud>
            <distancia unidades="km">15.3</distancia>
        </puntoAnonimo>

        <!-- Ribera d'Ebre: Ginestar a El Perelló -->
        <puntoAnonimo>
            <nombre>Ginestar</nombre>
            <longitud unidades="grados">0.6332</longitud>
            <latitud unidades="grados">41.0425</latitud>
            <altitud unidades="m">26</altitud>
            <distancia unidades="km">24.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Cruce T-302 (Rasquera)</nombre>
            <longitud unidades="grados">0.5954</longitud>
            <latitud unidades="grados">41.0011</latitud>
            <altitud unidades="m">130</altitud>
            <distancia unidades="km">30.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Tramo intermedio T-302</nombre>
            <longitud unidades="grados">0.6512</longitud>
            <latitud unidades="grados">40.9345</latitud>
            <altitud unidades="m">205</altitud>
            <distancia unidades="km">40.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>El Perelló</nombre>
            <longitud unidades="grados">0.7118</longitud>
            <latitud unidades="grados">40.8741</latitud>
            <altitud unidades="m">157</altitud>
            <distancia unidades="km">49.5</distancia>
        </puntoAnonimo>

        <!-- Zona Costa y Delta: L'Ampolla a Amposta -->
        <puntoAnonimo>
            <nombre>L'Ampolla</nombre>
            <longitud unidades="grados">0.7093</longitud>
            <latitud unidades="grados">40.8105</latitud>
            <altitud unidades="m">13</altitud>
            <distancia unidades="km">58.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Deltebre</nombre>
            <longitud unidades="grados">0.7281</longitud>
            <latitud unidades="grados">40.7186</latitud>
            <altitud unidades="m">10</altitud>
            <distancia unidades="km">70.7</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Sant Jaume d'Enveja</nombre>
            <longitud unidades="grados">0.7165</longitud>
            <latitud unidades="grados">40.7104</latitud>
            <altitud unidades="m">5</altitud>
            <distancia unidades="km">72.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Amposta</nombre>
            <longitud unidades="grados">0.5788</longitud>
            <latitud unidades="grados">40.7052</latitud>
            <altitud unidades="m">10</altitud>
            <distancia unidades="km">83.8</distancia>
        </puntoAnonimo>

        <!-- Ascenso por el río Ebro: Tortosa a Benifallet -->
        <puntoAnonimo>
            <nombre>Ribera del Ebro </nombre>
            <longitud unidades="grados">0.5512</longitud>
            <latitud unidades="grados">40.7601</latitud>
            <altitud unidades="m">14</altitud>
            <distancia unidades="km">93.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Tortosa (Primer paso)</nombre>
            <longitud unidades="grados">0.5216</longitud>
            <latitud unidades="grados">40.8124</latitud>
            <altitud unidades="m">10</altitud>
            <distancia unidades="km">101.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Bitem</nombre>
            <longitud unidades="grados">0.5255</longitud>
            <latitud unidades="grados">40.8521</latitud>
            <altitud unidades="m">18</altitud>
            <distancia unidades="km">107.8</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Paso por Tivenys</nombre>
            <longitud unidades="grados">0.5123</longitud>
            <latitud unidades="grados">40.9083</latitud>
            <altitud unidades="m">15</altitud>
            <distancia unidades="km">114.7</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Benifallet</nombre>
            <longitud unidades="grados">0.5281</longitud>
            <latitud unidades="grados">40.9754</latitud>
            <altitud unidades="m">18</altitud>
            <distancia unidades="km">126.9</distancia>
        </puntoAnonimo>

        <!-- Zona de montaña: Ascenso hacia Paüls -->
        <puntoAnonimo>
            <nombre>Rotonda Prat de Comte</nombre>
            <longitud unidades="grados">0.4905</longitud>
            <latitud unidades="grados">40.9902</latitud>
            <altitud unidades="m">90</altitud>
            <distancia unidades="km">133.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Inicio ascenso Puerto</nombre>
            <longitud unidades="grados">0.4208</longitud>
            <latitud unidades="grados">40.9351</latitud>
            <altitud unidades="m">130</altitud>
            <distancia unidades="km">144.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Cima Puerto de Paüls</nombre>
            <longitud unidades="grados">0.4005</longitud>
            <latitud unidades="grados">40.9238</latitud>
            <altitud unidades="m">381</altitud>
            <distancia unidades="km">148.4</distancia>
        </puntoAnonimo>

        <!-- Bajada y final: Xerta a Roquetes -->
        <puntoAnonimo>
            <nombre>Paüls (Exterior)</nombre>
            <longitud unidades="grados">0.4158</longitud>
            <latitud unidades="grados">40.9152</latitud>
            <altitud unidades="m">290</altitud>
            <distancia unidades="km">151.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Xerta</nombre>
            <longitud unidades="grados">0.4912</longitud>
            <latitud unidades="grados">40.9056</latitud>
            <altitud unidades="m">12</altitud>
            <distancia unidades="km">159.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
